config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root "todo_lists#index"

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :toggle
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  validates :title, presence: true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items, -> { order(id: :desc) }, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_items
  before_action :set_todo_item, only: [:show, :edit, :update, :toggle, :destroy]

  def show
  end

  def create
    @todo_item = @todo_items.build(safe_params)

    respond_to do |format|
      if @todo_item.save
        flash[:notice] = "Added"

        format.turbo_stream {  }
        format.html { redirect_to todo_list_path(@todo_list) }
      else
        flash[:alert] = "Error"

        format.turbo_stream { render "alert" }
        format.html { redirect_to todo_list_path(@todo_list) }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @todo_item.update(safe_params)
        flash[:notice] = "Updated"

        format.turbo_stream
        format.html { redirect_to todo_list_path(@todo_list) }
      else
        flash[:alert] = "Error"

        format.turbo_stream { render "alert" }
        format.html { redirect_to todo_list_path(@todo_list) }
      end
    end
  end

  def toggle
    @todo_item.toggle!(:done)

    flash[:notice] = "Done" if @todo_item.done?

    respond_to do |format|
      format.turbo_stream {}
      format.html { redirect_to todo_list_path(@todo_list) }
    end
  end

  def destroy
    respond_to do |format|
      if @todo_item.destroy
        flash[:notice] = "Deleted"

        format.turbo_stream {}
        format.html { redirect_to todo_list_path(@todo_list) }
      else
        flash[:alert] = "Error"

        format.turbo_stream { render "alert" }
        format.html { redirect_to todo_list_path(@todo_list) }
      end
    end
  end

  private

  def safe_params
    params.require(:todo_item).permit(:title)
  end

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_items
    @todo_items = @todo_list.todo_items
  end

  def set_todo_item
    @todo_item = @todo_items.find(params[:id])
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  def index
    @todo_lists = TodoList.all
  end

  def show
    @todo_list = TodoList.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/application/_alert_flash.html.erb
<% if flash[:alert] %>
  <div data-controller="flash" class="alert alert-danger shadow-lg">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/application/_flashes.html.erb
<div id="application-flashes" class="container position-fixed bottom-0 start-50 translate-middle-x">
  <%= render "alert_flash" %>
  <%= render "notice_flash" %>
</div>

app/views/application/_notice_flash.html.erb
<% if flash[:notice] %>
  <div data-controller="flash" class="alert alert-primary shadow-lg">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Hello world!</h1>

app/views/todo_items/_edit_item.html.erb
<li id="<%= dom_id(todo_item) %>" class="list-group-item">
  <div class="row align-items-center">
    <div class="col col-auto">
      <%= form_with model: todo_item, url: "" do |f| %>
        <%= f.check_box :done, class: "form-check-input", disabled: true %>
      <% end %>
    </div>
    <div class="col fs-5">
      <%= form_for [todo_item.todo_list, todo_item], id: dom_id(todo_item, "edit") do |f| %>
        <%= f.text_field :title, class: "form-control", placeholder: "Item title..." %>
      <% end %>
    </div>
    <div class="col col-auto">
      <div class="btn-group">
        <button title="Save" class="btn btn-outline-secondary" type="submit" form="<%= dom_id(todo_item, "edit") %>">
          <i class="bi bi-floppy-fill"></i>
        </button>
        <%= link_to [todo_item.todo_list, todo_item], title: "Cancel", data: {turbo_stream: true}, class: "btn btn-outline-secondary" do %>
          <i class="bi bi-x-circle"></i>
        <% end %>
      </div>
    </div>
  </div>
</li>

app/views/todo_items/_new_item.html.erb
<%= form_for [todo_list, todo_item], data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}, html: {class: "my-4"} do |f| %>
  <div class="input-group">
    <%= f.text_field :title, placeholder: "New item...", class: "form-control form-control-lg" %>
    <%= f.submit "Add", class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/todo_items/_todo_item.html.erb
<li id="<%= dom_id(todo_item) %>" class="list-group-item">
  <div class="row align-items-center">
    <div class="col col-auto">
      <%= form_with model: todo_item, url: toggle_todo_list_todo_item_path(todo_item.todo_list, todo_item), method: :patch, data: {controller: "toggle-todo-item"} do |f| %>
        <%= f.check_box :done, id: dom_id(todo_item, "toggle"), data: {action: "toggle-todo-item#toggle"}, class: "form-check-input" %>
      <% end %>
    </div>
    <div class="<%= class_names("col", "fs-5", "text-decoration-line-through": todo_item.done?) %>">
      <%= todo_item.title %>
    </div>
    <div class="col col-auto">
      <div class="btn-group">
        <%= link_to edit_todo_list_todo_item_path(todo_item.todo_list, todo_item), title: "Edit", data: {turbo_stream: true}, class: "btn btn-outline-secondary" do %>
          <i class="bi bi-pencil-square"></i>
        <% end %>
        <%= link_to [todo_item.todo_list, todo_item], title: "Delete", data: {turbo_confirm: "Are you sure?", turbo_method: :delete}, class: "btn btn-outline-secondary" do %>
          <i class="bi bi-trash3-fill"></i>
        <% end %>
      </div>
    </div>
  </div>
</li>

app/views/todo_items/_todo_items.html.erb
<div id="todo-items" class="card my-4 shadow-sm">
  <ul class="list-group list-group-flush">
    <%= render todo_items %>
    <% if todo_items.empty? %>
      <li class="list-group-item text-center p-5 fs-1">
        <i class="bi bi-check2-square"></i> Nothing to do
      </li>
    <% end %>
  </ul>
</div>

app/views/todo_items/alert.turbo_stream.erb
<%= turbo_stream.update "application-flashes", partial: "alert_flash" %>

app/views/todo_items/create.turbo_stream.erb
<%= turbo_stream.replace "todo-items", partial: "todo_items", locals: {todo_items: @todo_items} %>
<%= turbo_stream.update "application-flashes", partial: "notice_flash" %>

app/views/todo_items/destroy.turbo_stream.erb
<%= turbo_stream.replace "todo-items", partial: "todo_items", locals: {todo_items: @todo_items} %>
<%= turbo_stream.update "application-flashes", partial: "notice_flash" %>

app/views/todo_items/edit.html.erb
<%= render "edit_item", todo_item: @todo_item %>

app/views/todo_items/edit.turbo_stream.erb
<%= turbo_stream.replace @todo_item, partial: "edit_item", locals: {todo_item: @todo_item} %>

app/views/todo_items/show.html.erb
<%= render @todo_item %>

app/views/todo_items/show.turbo_stream.erb
<%= turbo_stream.replace @todo_item %>

app/views/todo_items/toggle.turbo_stream.erb
<%= turbo_stream.replace @todo_item %>
<%= turbo_stream.update "application-flashes" do %>
  <% if @todo_item.done? %>
    <%= render "notice_flash" %>
  <% end %>
<% end %>

app/views/todo_items/update.turbo_stream.erb
<%= turbo_stream.replace @todo_item %>
<%= turbo_stream.update "application-flashes", partial: "notice_flash" %>

app/views/todo_lists/index.html.erb
<h1 class="display-1 text-center mt-4">My Todo Lists</h1>

<div class="card my-4 shadow-sm">
  <ul class="list-group list-group-flush">
    <% @todo_lists.each do |list| %>
      <li class="list-group-item fs-5">
        <%= link_to list.name, list %>
      </li>
    <% end %>
  </ul>
</div>

app/views/todo_lists/show.html.erb
<h1 class="display-1 text-center mt-4"><%= @todo_list.name %></h1>

<%= render "todo_items/new_item", todo_list: @todo_list, todo_item: TodoItem.new %>

<%= render "todo_items/todo_items", todo_items: @todo_list.todo_items %>

<%= render "application/flashes" %>